import { useEffect, useState } from 'react';
import { api } from '../api';

const empty = { periodStart: '', periodEnd: '', totalWorkOrders: '', completedWorkOrders: '', totalLaborHours: '', downtimeHours: '', totalMaintenanceCost: '', complianceNotes: '', generatedBy: '' };

export default function Reports() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState(null);
  const [form, setForm] = useState(empty);

  const load = () => api.reports.list(100).then(r => { setItems(r.data); setLoading(false); }).catch(() => { setItems([]); setLoading(false); });
  useEffect(() => { load(); }, []);

  function openNew() { setForm(empty); setModal('new'); }
  function openEdit(item) {
    setForm({ periodStart: item.periodStart?.slice(0,10) || '', periodEnd: item.periodEnd?.slice(0,10) || '', totalWorkOrders: item.totalWorkOrders || '', completedWorkOrders: item.completedWorkOrders || '', totalLaborHours: item.totalLaborHours || '', downtimeHours: item.downtimeHours || '', totalMaintenanceCost: item.totalMaintenanceCost || '', complianceNotes: item.complianceNotes || '', generatedBy: item.generatedBy || '' });
    setModal(item);
  }

  async function save() {
    if (modal === 'new') await api.reports.create(form);
    else await api.reports.update(modal.id, form);
    setModal(null); load();
  }

  async function remove(id) { if (!confirm('Delete?')) return; await api.reports.remove(id); load(); }
  const set = (k, v) => setForm(prev => ({ ...prev, [k]: v }));

  function fmtDate(d) { return d ? new Date(d).toLocaleDateString() : '—'; }

  return (
    <div>
      <div className="page-header">
        <div><h1>📊 Maintenance Reports</h1><div className="subtitle">Analytics, downtime & compliance</div></div>
        <button className="btn btn-primary" onClick={openNew}>+ New Report</button>
      </div>
      <div className="card">
        {loading ? <div className="loading">Loading...</div> :
        items.length === 0 ? <div className="empty">No reports yet.</div> :
        <table>
          <thead><tr><th>Period</th><th>Work Orders</th><th>Completed</th><th>Labor Hrs</th><th>Downtime Hrs</th><th>Cost</th><th>Actions</th></tr></thead>
          <tbody>
            {items.map(r => (
              <tr key={r.id}>
                <td>{fmtDate(r.periodStart)} — {fmtDate(r.periodEnd)}</td>
                <td>{r.totalWorkOrders}</td>
                <td>{r.completedWorkOrders}</td>
                <td>{r.totalLaborHours}</td>
                <td>{r.downtimeHours}</td>
                <td>${Number(r.totalMaintenanceCost || 0).toLocaleString()}</td>
                <td>
                  <button className="btn btn-secondary btn-sm" onClick={() => openEdit(r)}>Edit</button>{' '}
                  <button className="btn btn-danger btn-sm" onClick={() => remove(r.id)}>Delete</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>}
      </div>
      {modal && (
        <div className="modal-overlay" onClick={() => setModal(null)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <h2>{modal === 'new' ? 'New Report' : 'Edit Report'}</h2>
            <div className="form-row">
              <div className="form-group"><label>Period Start *</label><input type="date" value={form.periodStart} onChange={e => set('periodStart', e.target.value)} /></div>
              <div className="form-group"><label>Period End *</label><input type="date" value={form.periodEnd} onChange={e => set('periodEnd', e.target.value)} /></div>
            </div>
            <div className="form-row">
              <div className="form-group"><label>Total Work Orders</label><input type="number" value={form.totalWorkOrders} onChange={e => set('totalWorkOrders', e.target.value)} /></div>
              <div className="form-group"><label>Completed</label><input type="number" value={form.completedWorkOrders} onChange={e => set('completedWorkOrders', e.target.value)} /></div>
            </div>
            <div className="form-row">
              <div className="form-group"><label>Labor Hours</label><input type="number" value={form.totalLaborHours} onChange={e => set('totalLaborHours', e.target.value)} /></div>
              <div className="form-group"><label>Downtime Hours</label><input type="number" value={form.downtimeHours} onChange={e => set('downtimeHours', e.target.value)} /></div>
            </div>
            <div className="form-row">
              <div className="form-group"><label>Total Cost</label><input type="number" value={form.totalMaintenanceCost} onChange={e => set('totalMaintenanceCost', e.target.value)} /></div>
              <div className="form-group"><label>Generated By</label><input value={form.generatedBy} onChange={e => set('generatedBy', e.target.value)} /></div>
            </div>
            <div className="form-group"><label>Compliance Notes</label><textarea value={form.complianceNotes} onChange={e => set('complianceNotes', e.target.value)} /></div>
            <div className="modal-actions">
              <button className="btn btn-secondary" onClick={() => setModal(null)}>Cancel</button>
              <button className="btn btn-primary" onClick={save}>Save</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
